version: '3.9'

services:
  api:
    build:
      context: ./BankingSolutionBackend/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Data Source=/app/db.sqlite
    volumes:
      - db-data:/app

volumes:
  db-data: